### ISSUE TITLE
moduleFilename option doesn't work for chunkFilename

### ISSUE THREAD

**Issue by sh-a-v** [webpack-contrib/mini-css-extract-plugin#437] opened 2019-07-30 21:36 UTC
- Operating System: debian
- Node Version: 10.15.3
- NPM Version: 6.4.1
- webpack Version: 4.37.0
- mini-css-extract-plugin Version: 0.8.0

### Expected Behavior

Change chunkFilename of the outputted file

### Actual Behavior

Nothing changes, the default filename option is used

**Comment by evilebottnawi** [comment] 2019-07-31 10:01
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Without reproducible test repo we can't help

**Closed by evilebottnawi** 2019-07-31 10:01 UTC

**Comment by kylerberry** [comment] 2019-10-16 16:33
@sh-a-v upgraded mini-css-extract-plugin to `0.7.0` fixed a similar issue for me
