### ISSUE TITLE
Error: webpack.config.js:664  new MiniCssExtractPlugin({ ^  TypeError: MiniCssExtractPlugin is not a constructor

### ISSUE THREAD

**Issue by icurto2020** [webpack-contrib/mini-css-extract-plugin#898] opened 2022-01-16 14:04 UTC
How to reproduce (Node)
npx create-react-app test
cd test
npm run build

webpack.config.js:664
        new MiniCssExtractPlugin({^
TypeError: MiniCssExtractPlugin is not a constructor

**Comment by snitin315** [comment] 2022-01-16 14:07
Duplicate of #896

**Closed by snitin315** 2022-01-16 14:07 UTC

**Comment by jathanasiou** [comment] 2022-01-17 14:15
For reference, this seems to be the root cause of https://github.com/facebook/create-react-app/issues/11930
