### ISSUE TITLE
adding splitChunks all is breaking the module exports 

### ISSUE THREAD

**Issue by varenya** [webpack-contrib/mini-css-extract-plugin#408] opened 2019-06-11 15:25 UTC
* Operating System:  macOS mojave
* Node Version: v11.3.0
* NPM Version: 6.7.0
* webpack Version: 4.33.0
* mini-css-extract-plugin Version: 0.7.0

### Expected Behavior

Having concatenated all CSS in the file should not break the module exports. 

### Actual Behavior

Adding the splitChunks optimization for a single css file is breaking the umd build exports.

### Code

```js
optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
```

### How Do We Reproduce?

- create with umd build as output and configure the optimization rule and try and importing the component from the library. it fails with error 

TypeError: Cannot read property <functionName> of undefined

**Comment by evilebottnawi** [comment] 2019-06-11 16:13
Looks you have old global installed webpack, if not, please create minimum reproducible test repo

**Comment by varenya** [comment] 2019-06-12 16:56
No, I don't have globally installed webpack. I will try and create a minimum reproducible test repo.

**Comment by varenya** [comment] 2019-06-12 18:45
Heres the repo with the minimum reproducible test: https://github.com/varenya/webpack-reprod

**Comment by varenya** [comment] 2019-06-15 05:36
@evilebottnawi I have reproduced the issue could u take a look? thanks.

**Comment by evilebottnawi** [comment] 2019-07-16 20:05
@varenya can't run you reproducible test repo, i will always got `Module not found: Error: Can't resolve 'sample-package/style.css'`

**Comment by kalbert312** [comment] 2019-09-09 15:07
I'm running into this problem as well. My main module's import is undefined with the splitChunks block. Removing it fixed the problem. Target UMD.

**Comment by evilebottnawi** [comment] 2019-09-09 15:23
@kalbert312 can you create minimum reproducible test repo?

**Comment by kalbert312** [comment] 2019-09-09 16:02
Done. Not super minimal but I reproduced the problem.
Repo: https://github.com/kalbert312/main-module-undefined

Steps:
1. Add `"main-module-undefined": "git+ssh://git@github.com/kalbert312/main-module-undefined.git#good",` to your project's package.json and run npm install.
2. Add this to your project somewhere:
```javascript
import * as MainModule from "main-module-undefined";
console.log("Module: ", MainModule);
```
3. Run it and see that the export is as expected.
4. Change the dependency version to `"main-module-undefined": "git+ssh://git@github.com/kalbert312/main-module-undefined.git#bad" and run `npm install` again.
5. Run project again. `MainModule` is `undefined`.

**Comment by evilebottnawi** [comment] 2019-09-09 16:13
What about this https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free?

**Comment by kalbert312** [comment] 2019-09-09 16:22
Looks like that did the trick for me: https://github.com/kalbert312/main-module-undefined/tree/maybe-bad

**Comment by evilebottnawi** [comment] 2019-09-09 16:25
I think we should output better error for this case

**Comment by kalbert312** [comment] 2019-09-09 18:14
I was focusing on the JS imports instead of the CSS import. Looks like adding the `sideEffects: false` fixed the JS import, but now the styles chunk is completely missing from the dist. Going to see if I can run two builds to work around it.

**Comment by kalbert312** [comment] 2019-09-09 20:39
After more digging, it looks like the extra JS file produced might be the cause?. Something isn't getting executed.

1.index.js:
```javascript
(this["webpackJsonpmymodule"] = this["webpackJsonpmymodule"] || []).push([[1],{

/***/ 6:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ }),

/***/ 7:
/***/ (function(module, exports, __webpack_require__) {

// extracted by mini-css-extract-plugin

/***/ })

}]);
//# sourceMappingURL=1.index.js.map
```
When this file gets generated, the main js file has different code generated:

Good:
```javascript
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 9);
```

Bad:
```javascript
	return /******/ (function(modules) { // webpackBootstrap
		/******/ 	// install a JSONP callback for chunk loading
		/******/ 	function webpackJsonpCallback(data) {
			/******/ 		var chunkIds = data[0];
			/******/ 		var moreModules = data[1];
			/******/ 		var executeModules = data[2];
			/******/
			/******/ 		// add "moreModules" to the modules object,
			/******/ 		// then flag all "chunkIds" as loaded and fire callback
			/******/ 		var moduleId, chunkId, i = 0, resolves = [];
			/******/ 		for(;i < chunkIds.length; i++) {
				/******/ 			chunkId = chunkIds[i];
				/******/ 			if(Object.prototype.hasOwnProperty.call(installedChunks, chunkId) && installedChunks[chunkId]) {
					/******/ 				resolves.push(installedChunks[chunkId][0]);
					/******/ 			}
				/******/ 			installedChunks[chunkId] = 0;
				/******/ 		}
			/******/ 		for(moduleId in moreModules) {
				/******/ 			if(Object.prototype.hasOwnProperty.call(moreModules, moduleId)) {
					/******/ 				modules[moduleId] = moreModules[moduleId];
					/******/ 			}
				/******/ 		}
			/******/ 		if(parentJsonpFunction) parentJsonpFunction(data);
			/******/
			/******/ 		while(resolves.length) {
				/******/ 			resolves.shift()();
				/******/ 		}
			/******/
			/******/ 		// add entry modules from loaded chunk to deferred list
			/******/ 		deferredModules.push.apply(deferredModules, executeModules || []);
			/******/
			/******/ 		// run deferred modules when all chunks ready
			/******/ 		return checkDeferredModules();
			/******/ 	};
		/******/ 	function checkDeferredModules() {
			/******/ 		var result;
			/******/ 		for(var i = 0; i < deferredModules.length; i++) {
				/******/ 			var deferredModule = deferredModules[i];
				/******/ 			var fulfilled = true;
				/******/ 			for(var j = 1; j < deferredModule.length; j++) {
					/******/ 				var depId = deferredModule[j];
					/******/ 				if(installedChunks[depId] !== 0) fulfilled = false;
					/******/ 			}
				/******/ 			if(fulfilled) {
					/******/ 				deferredModules.splice(i--, 1);
					/******/ 				result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
					/******/ 			}
				/******/ 		}
			/******/
			/******/ 		return result;
			/******/ 	}
		/******/
		/******/ 	// The module cache
		/******/ 	var installedModules = {};
		/******/
		/******/ 	// object to store loaded and loading chunks
		/******/ 	// undefined = chunk not loaded, null = chunk preloaded/prefetched
		/******/ 	// Promise = chunk loading, 0 = chunk loaded
		/******/ 	var installedChunks = {
			/******/ 		0: 0
			/******/ 	};
		/******/
		/******/ 	var deferredModules = [];
		/******/
		/******/ 	// The require function
		/******/ 	function __webpack_require__(moduleId) {
			/******/
			/******/ 		// Check if module is in cache
			/******/ 		if(installedModules[moduleId]) {
				/******/ 			return installedModules[moduleId].exports;
				/******/ 		}
			/******/ 		// Create a new module (and put it into the cache)
			/******/ 		var module = installedModules[moduleId] = {
				/******/ 			i: moduleId,
				/******/ 			l: false,
				/******/ 			exports: {}
				/******/ 		};
			/******/
			/******/ 		// Execute the module function
			/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
			/******/
			/******/ 		// Flag the module as loaded
			/******/ 		module.l = true;
			/******/
			/******/ 		// Return the exports of the module
			/******/ 		return module.exports;
			/******/ 	}
		/******/
		/******/
		/******/ 	// expose the modules object (__webpack_modules__)
		/******/ 	__webpack_require__.m = modules;
		/******/
		/******/ 	// expose the module cache
		/******/ 	__webpack_require__.c = installedModules;
		/******/
		/******/ 	// define getter function for harmony exports
		/******/ 	__webpack_require__.d = function(exports, name, getter) {
			/******/ 		if(!__webpack_require__.o(exports, name)) {
				/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
				/******/ 		}
			/******/ 	};
		/******/
		/******/ 	// define __esModule on exports
		/******/ 	__webpack_require__.r = function(exports) {
			/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
				/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
				/******/ 		}
			/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
			/******/ 	};
		/******/
		/******/ 	// create a fake namespace object
		/******/ 	// mode & 1: value is a module id, require it
		/******/ 	// mode & 2: merge all properties of value into the ns
		/******/ 	// mode & 4: return value when already ns object
		/******/ 	// mode & 8|1: behave like require
		/******/ 	__webpack_require__.t = function(value, mode) {
			/******/ 		if(mode & 1) value = __webpack_require__(value);
			/******/ 		if(mode & 8) return value;
			/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
			/******/ 		var ns = Object.create(null);
			/******/ 		__webpack_require__.r(ns);
			/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
			/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
			/******/ 		return ns;
			/******/ 	};
		/******/
		/******/ 	// getDefaultExport function for compatibility with non-harmony modules
		/******/ 	__webpack_require__.n = function(module) {
			/******/ 		var getter = module && module.__esModule ?
				/******/ 			function getDefault() { return module['default']; } :
				/******/ 			function getModuleExports() { return module; };
			/******/ 		__webpack_require__.d(getter, 'a', getter);
			/******/ 		return getter;
			/******/ 	};
		/******/
		/******/ 	// Object.prototype.hasOwnProperty.call
		/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
		/******/
		/******/ 	// __webpack_public_path__
		/******/ 	__webpack_require__.p = "";
		/******/
		/******/ 	var jsonpArray = this["webpackJsonpmymodule"] = this["webpackJsonpmymodule"] || [];
		/******/ 	var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);
		/******/ 	jsonpArray.push = webpackJsonpCallback;
		/******/ 	jsonpArray = jsonpArray.slice();
		/******/ 	for(var i = 0; i < jsonpArray.length; i++) webpackJsonpCallback(jsonpArray[i]);
		/******/ 	var parentJsonpFunction = oldJsonpFunction;
		/******/
		/******/
		/******/ 	// add entry module to deferred list
		/******/ 	deferredModules.push([11,1]);
		/******/ 	// run deferred modules when ready
		/******/ 	return checkDeferredModules();
		/******/ })
```

**Comment by evilebottnawi** [comment] 2019-09-10 09:56
@kalbert312 it is in my todo list, look on this in near future (today/tomorrow)

**Comment by evilebottnawi** [comment] 2019-09-16 13:33
You should not use `sideEffects: false`, because css is `sideEffects` always

**Comment by evilebottnawi** [comment] 2019-09-16 13:35
I can't reproduce, what is branch i should use?

**Comment by kalbert312** [comment] 2019-09-17 14:30
`bad` and `maybe-bad` have bad bundles (importing the JS bundle elsewhere should result in `undefined`).

**Comment by ianks** [comment] 2019-10-30 03:30
i believe we may be experiencing a similar issue. however, if we set `maxInitialChunks: Infinity`. does that happen with your build @kalbert312 ?

**Comment by giuseppeg** [comment] 2019-12-12 11:40
I am experiencing the same issue and the setup is the one from @kalbert312's testcase. 
@evilebottnawi can I help in any way?

**Comment by tylerexmg** [comment] 2019-12-13 15:35
> After more digging, it looks like the extra JS file produced might be the cause?. Something isn't getting executed.
> 
> 1.index.js:
> 
> ```js
> (this["webpackJsonpmymodule"] = this["webpackJsonpmymodule"] || []).push([[1],{
> 
> /***/ 6:
> /***/ (function(module, exports, __webpack_require__) {
> 
> // extracted by mini-css-extract-plugin
> 
> /***/ }),
> 
> /***/ 7:
> /***/ (function(module, exports, __webpack_require__) {
> 
> // extracted by mini-css-extract-plugin
> 
> /***/ })
> 
> }]);
> //# sourceMappingURL=1.index.js.map
> ```
> 
> When this file gets generated, the main js file has different code generated:
> 
> Good:
> 
> ```js
> return /******/ (function(modules) { // webpackBootstrap
> /******/ 	// The module cache
> /******/ 	var installedModules = {};
> /******/
> /******/ 	// The require function
> /******/ 	function __webpack_require__(moduleId) {
> /******/
> /******/ 		// Check if module is in cache
> /******/ 		if(installedModules[moduleId]) {
> /******/ 			return installedModules[moduleId].exports;
> /******/ 		}
> /******/ 		// Create a new module (and put it into the cache)
> /******/ 		var module = installedModules[moduleId] = {
> /******/ 			i: moduleId,
> /******/ 			l: false,
> /******/ 			exports: {}
> /******/ 		};
> /******/
> /******/ 		// Execute the module function
> /******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
> /******/
> /******/ 		// Flag the module as loaded
> /******/ 		module.l = true;
> /******/
> /******/ 		// Return the exports of the module
> /******/ 		return module.exports;
> /******/ 	}
> /******/
> /******/
> /******/ 	// expose the modules object (__webpack_modules__)
> /******/ 	__webpack_require__.m = modules;
> /******/
> /******/ 	// expose the module cache
> /******/ 	__webpack_require__.c = installedModules;
> /******/
> /******/ 	// define getter function for harmony exports
> /******/ 	__webpack_require__.d = function(exports, name, getter) {
> /******/ 		if(!__webpack_require__.o(exports, name)) {
> /******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
> /******/ 		}
> /******/ 	};
> /******/
> /******/ 	// define __esModule on exports
> /******/ 	__webpack_require__.r = function(exports) {
> /******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
> /******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
> /******/ 		}
> /******/ 		Object.defineProperty(exports, '__esModule', { value: true });
> /******/ 	};
> /******/
> /******/ 	// create a fake namespace object
> /******/ 	// mode & 1: value is a module id, require it
> /******/ 	// mode & 2: merge all properties of value into the ns
> /******/ 	// mode & 4: return value when already ns object
> /******/ 	// mode & 8|1: behave like require
> /******/ 	__webpack_require__.t = function(value, mode) {
> /******/ 		if(mode & 1) value = __webpack_require__(value);
> /******/ 		if(mode & 8) return value;
> /******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
> /******/ 		var ns = Object.create(null);
> /******/ 		__webpack_require__.r(ns);
> /******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
> /******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
> /******/ 		return ns;
> /******/ 	};
> /******/
> /******/ 	// getDefaultExport function for compatibility with non-harmony modules
> /******/ 	__webpack_require__.n = function(module) {
> /******/ 		var getter = module && module.__esModule ?
> /******/ 			function getDefault() { return module['default']; } :
> /******/ 			function getModuleExports() { return module; };
> /******/ 		__webpack_require__.d(getter, 'a', getter);
> /******/ 		return getter;
> /******/ 	};
> /******/
> /******/ 	// Object.prototype.hasOwnProperty.call
> /******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
> /******/
> /******/ 	// __webpack_public_path__
> /******/ 	__webpack_require__.p = "";
> /******/
> /******/
> /******/ 	// Load entry module and return exports
> /******/ 	return __webpack_require__(__webpack_require__.s = 9);
> ```
> 
> Bad:
> 
> ```js
> 	return /******/ (function(modules) { // webpackBootstrap
> 		/******/ 	// install a JSONP callback for chunk loading
> 		/******/ 	function webpackJsonpCallback(data) {
> 			/******/ 		var chunkIds = data[0];
> 			/******/ 		var moreModules = data[1];
> 			/******/ 		var executeModules = data[2];
> 			/******/
> 			/******/ 		// add "moreModules" to the modules object,
> 			/******/ 		// then flag all "chunkIds" as loaded and fire callback
> 			/******/ 		var moduleId, chunkId, i = 0, resolves = [];
> 			/******/ 		for(;i < chunkIds.length; i++) {
> 				/******/ 			chunkId = chunkIds[i];
> 				/******/ 			if(Object.prototype.hasOwnProperty.call(installedChunks, chunkId) && installedChunks[chunkId]) {
> 					/******/ 				resolves.push(installedChunks[chunkId][0]);
> 					/******/ 			}
> 				/******/ 			installedChunks[chunkId] = 0;
> 				/******/ 		}
> 			/******/ 		for(moduleId in moreModules) {
> 				/******/ 			if(Object.prototype.hasOwnProperty.call(moreModules, moduleId)) {
> 					/******/ 				modules[moduleId] = moreModules[moduleId];
> 					/******/ 			}
> 				/******/ 		}
> 			/******/ 		if(parentJsonpFunction) parentJsonpFunction(data);
> 			/******/
> 			/******/ 		while(resolves.length) {
> 				/******/ 			resolves.shift()();
> 				/******/ 		}
> 			/******/
> 			/******/ 		// add entry modules from loaded chunk to deferred list
> 			/******/ 		deferredModules.push.apply(deferredModules, executeModules || []);
> 			/******/
> 			/******/ 		// run deferred modules when all chunks ready
> 			/******/ 		return checkDeferredModules();
> 			/******/ 	};
> 		/******/ 	function checkDeferredModules() {
> 			/******/ 		var result;
> 			/******/ 		for(var i = 0; i < deferredModules.length; i++) {
> 				/******/ 			var deferredModule = deferredModules[i];
> 				/******/ 			var fulfilled = true;
> 				/******/ 			for(var j = 1; j < deferredModule.length; j++) {
> 					/******/ 				var depId = deferredModule[j];
> 					/******/ 				if(installedChunks[depId] !== 0) fulfilled = false;
> 					/******/ 			}
> 				/******/ 			if(fulfilled) {
> 					/******/ 				deferredModules.splice(i--, 1);
> 					/******/ 				result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
> 					/******/ 			}
> 				/******/ 		}
> 			/******/
> 			/******/ 		return result;
> 			/******/ 	}
> 		/******/
> 		/******/ 	// The module cache
> 		/******/ 	var installedModules = {};
> 		/******/
> 		/******/ 	// object to store loaded and loading chunks
> 		/******/ 	// undefined = chunk not loaded, null = chunk preloaded/prefetched
> 		/******/ 	// Promise = chunk loading, 0 = chunk loaded
> 		/******/ 	var installedChunks = {
> 			/******/ 		0: 0
> 			/******/ 	};
> 		/******/
> 		/******/ 	var deferredModules = [];
> 		/******/
> 		/******/ 	// The require function
> 		/******/ 	function __webpack_require__(moduleId) {
> 			/******/
> 			/******/ 		// Check if module is in cache
> 			/******/ 		if(installedModules[moduleId]) {
> 				/******/ 			return installedModules[moduleId].exports;
> 				/******/ 		}
> 			/******/ 		// Create a new module (and put it into the cache)
> 			/******/ 		var module = installedModules[moduleId] = {
> 				/******/ 			i: moduleId,
> 				/******/ 			l: false,
> 				/******/ 			exports: {}
> 				/******/ 		};
> 			/******/
> 			/******/ 		// Execute the module function
> 			/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
> 			/******/
> 			/******/ 		// Flag the module as loaded
> 			/******/ 		module.l = true;
> 			/******/
> 			/******/ 		// Return the exports of the module
> 			/******/ 		return module.exports;
> 			/******/ 	}
> 		/******/
> 		/******/
> 		/******/ 	// expose the modules object (__webpack_modules__)
> 		/******/ 	__webpack_require__.m = modules;
> 		/******/
> 		/******/ 	// expose the module cache
> 		/******/ 	__webpack_require__.c = installedModules;
> 		/******/
> 		/******/ 	// define getter function for harmony exports
> 		/******/ 	__webpack_require__.d = function(exports, name, getter) {
> 			/******/ 		if(!__webpack_require__.o(exports, name)) {
> 				/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
> 				/******/ 		}
> 			/******/ 	};
> 		/******/
> 		/******/ 	// define __esModule on exports
> 		/******/ 	__webpack_require__.r = function(exports) {
> 			/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
> 				/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
> 				/******/ 		}
> 			/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
> 			/******/ 	};
> 		/******/
> 		/******/ 	// create a fake namespace object
> 		/******/ 	// mode & 1: value is a module id, require it
> 		/******/ 	// mode & 2: merge all properties of value into the ns
> 		/******/ 	// mode & 4: return value when already ns object
> 		/******/ 	// mode & 8|1: behave like require
> 		/******/ 	__webpack_require__.t = function(value, mode) {
> 			/******/ 		if(mode & 1) value = __webpack_require__(value);
> 			/******/ 		if(mode & 8) return value;
> 			/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
> 			/******/ 		var ns = Object.create(null);
> 			/******/ 		__webpack_require__.r(ns);
> 			/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
> 			/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
> 			/******/ 		return ns;
> 			/******/ 	};
> 		/******/
> 		/******/ 	// getDefaultExport function for compatibility with non-harmony modules
> 		/******/ 	__webpack_require__.n = function(module) {
> 			/******/ 		var getter = module && module.__esModule ?
> 				/******/ 			function getDefault() { return module['default']; } :
> 				/******/ 			function getModuleExports() { return module; };
> 			/******/ 		__webpack_require__.d(getter, 'a', getter);
> 			/******/ 		return getter;
> 			/******/ 	};
> 		/******/
> 		/******/ 	// Object.prototype.hasOwnProperty.call
> 		/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
> 		/******/
> 		/******/ 	// __webpack_public_path__
> 		/******/ 	__webpack_require__.p = "";
> 		/******/
> 		/******/ 	var jsonpArray = this["webpackJsonpmymodule"] = this["webpackJsonpmymodule"] || [];
> 		/******/ 	var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);
> 		/******/ 	jsonpArray.push = webpackJsonpCallback;
> 		/******/ 	jsonpArray = jsonpArray.slice();
> 		/******/ 	for(var i = 0; i < jsonpArray.length; i++) webpackJsonpCallback(jsonpArray[i]);
> 		/******/ 	var parentJsonpFunction = oldJsonpFunction;
> 		/******/
> 		/******/
> 		/******/ 	// add entry module to deferred list
> 		/******/ 	deferredModules.push([11,1]);
> 		/******/ 	// run deferred modules when ready
> 		/******/ 	return checkDeferredModules();
> 		/******/ })
> ```

I have just observed this exact issue in my project and its lead me into a dead-end trying to split css. Hopefully it gets fixed soon.

**Comment by yazonnile** [comment] 2019-12-26 22:56
Guys, I dont know a root problem, but I makes this thing work for me.
splitChunks all generates two files.
1 - `styles.css` itself.
2- `styles.js` file with empty css files modules
And the problem is - this `styles.js` file is not used in main bundle file `index.js`

so in my html file
# was
```html
<script defer src="/index.js"></script>
```

# now
with `AutomaticPrefetchPlugin` for makes this work before main bundle
```html
<script defer src="/styles.js"></script>
<script defer src="/index.js"></script>
```

**Comment by Sellec** [comment] 2020-02-21 12:52
Have the same issue - i need to extract vue's components styles into one single css file and got two js files - bug "bundle.js" file and little (window[jsonp]) "0.bundle.js" file. Its annoying.

**Comment by Sellec** [comment] 2020-02-21 13:17
setting the splitchunks.cacheGroups.[chunkname].name='main' solves the problem with additional little file.
```
        splitChunks: {
            cacheGroups: {
                extractedCSS: {
                    test: (module, chunks) => module.constructor.name === 'CssModule',
                    name: "main",
                    chunks: "all",
                    enforce: true
                }
            }
        }
```

**Comment by rwieruch** [comment] 2020-12-20 16:52
Has someone been able to fix this problem? I got the same issue with Webpack 4 where I activate splitChunks and get undefined for my imports.

**Comment by powerfulwebdesign** [comment] 2021-01-27 10:17
I still have the problem :(

**Comment by jkarttunen** [comment] 2021-08-17 08:07
For me, it's a 600kb js file, consisting of only CSS classnames

**Comment by alexander-akait** [comment] 2021-09-06 17:36
Should be solved, only one problem is empty JS files, but it should be fixed in webpack itself https://github.com/webpack/webpack/issues/11671, if anybody will faced the the problem feel free to feedback and I will help

**Closed by alexander-akait** 2021-09-06 17:36 UTC

**Comment by bturner1273** [comment] 2022-03-04 17:08
[my split chunks css bundling issue example](https://github.com/bturner1273/webpack_splitchunks_minimum_bug_example)
I have a 'good' branch that doesn't include optimizations.splitChunks.chunks = 'all' and a 'bad' branch that does. The bad branch will not umd export to my client-side js correctly for whatever reason. I tried using MiniCssExtractPlugin to no avail
