### ISSUE TITLE
Empty styles after migration to webpack 4. 

### ISSUE THREAD

**Issue by Gorett** [webpack-contrib/mini-css-extract-plugin#567] opened 2020-08-25 09:00 UTC
Hi, there. I'm trying to update webpack version from 3-rd to 4-th. I've faced with strange issue. When I try to use `esModule: true,` option imported style modules are undefined. If this option is false I've received empty object. I think it, somehow, can be connected with postcss usage in the project. But I'm not sure. Maybe someone can help me with that.
Here is dev webpack config for client side rendering

```
const path = require('path');
const webpack = require('webpack');
const WriteFilePlugin = require('write-file-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const defineEnv = require('./dotenv');

const devMode = process.env.NODE_ENV !== 'production';

module.exports = {
	mode: 'development',
	name: 'client',
	target: 'web',
	devtool: 'source-map',
	entry: [
		'babel-polyfill',
		'fetch-everywhere',
		'webpack-hot-middleware/client?path=/__webpack_hmr&timeout=20000&reload=false&quiet=false&noInfo=false',
		'react-hot-loader/patch',
		path.resolve(__dirname, '../src/index.js'),
	],
	output: {
		filename: '[name].js',
		chunkFilename: '[name].js',
		path: path.resolve(__dirname, '../buildClient'),
		publicPath: '/static/',
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: 'babel-loader',
			},
			{
				test: /\.(sa|sc|c)ss$/,
				use: [
					{
						loader: MiniCssExtractPlugin.loader,
						options: {
							esModule: true,
							hmr: process.env.NODE_ENV === 'development',
							reloadAll: true,
						},
					},
					'css-loader',
					'postcss-loader',
				],
			},
			{
				test: /\.(png|jpg|gif)$/,
				use: [
					{
						loader: 'file-loader',
					},
				],
			},
		],
	},
	resolve: {
		extensions: ['.js', '.css'],
	},
	plugins: [
		new WriteFilePlugin(),
		new MiniCssExtractPlugin({
			filename: devMode ? '[name].css' : '[name].[hash].css',
			chunkFilename: devMode ? '[id].css' : '[id].[hash].css',
		}),
		new webpack.HotModuleReplacementPlugin(),
		new webpack.DefinePlugin(defineEnv),
	],
};
```

**Comment by Gorett** [comment] 2020-08-25 09:04
here is server side part. 
```
const fs = require('fs');
const path = require('path');
const webpack = require('webpack');
const defineEnvironment = require('./dotenv');

const res = p => path.resolve(__dirname, p);

// if you're specifying externals to leave unbundled, you need to tell Webpack
// to still bundle `react-universal-component`, `webpack-flush-chunks` and
// `require-universal-module` so that they know they are running
// within Webpack and can properly make connections to client modules:
const externals = fs
	.readdirSync(res('../node_modules'))
	.filter(
		x => !/\.bin|react-universal-component|require-universal-module|webpack-flush-chunks/.test(x),
	)
	.reduce((ext, mod) => {
		ext[mod] = `commonjs ${mod}`; // eslint-disable-line no-param-reassign
		return ext;
	}, {});

module.exports = {
	mode: 'development',
	name: 'server',
	target: 'node',
	devtool: 'source-map',
	entry: ['babel-polyfill', 'fetch-everywhere', res('../server/render.js')],
	externals,
	output: {
		path: res('../buildServer'),
		filename: '[name].js',
		libraryTarget: 'commonjs2',
		publicPath: '/static/',
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				exclude: /node_modules/,
				use: 'babel-loader',
			},
			{
				test: /\.css$/,
				exclude: /node_modules/,
				loader: 'css-loader',
				options: {
					import: true,
					url: true,
					modules: {
						compileType: 'module',
						mode: 'local',
						auto: true,
						exportGlobals: true,
						exportOnlyLocals: true,
						localIdentName: '[name]__[local]--[hash:base64:5]',
						namedExport: true,
					},
				},
			},
			{
				test: /\.(png|jpg|gif)$/,
				use: [
					{
						loader: 'file-loader',
					},
				],
			},
		],
	},
	resolve: {
		extensions: ['.js', '.css'],
	},
	plugins: [
		new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
		new webpack.DefinePlugin(defineEnvironment),
	],
};

```

**Comment by evilebottnawi** [comment] 2020-08-25 09:39
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

>  When I try to use esModule: true, option imported style modules are undefined.

Because you need to use `import` or `require('something').default`.

Please avoid copy/pasting configurations, it is not readable and impossible to debug, if you need help - just create reproducible test repo and create simple readme what you have and what you expected, I will reopen issue after fill out issue template or creating reproducible test repo, thanks

**Closed by evilebottnawi** 2020-08-25 09:39 UTC
