### ISSUE TITLE
extract css used by two or more chunks into a vendor chunk

### ISSUE THREAD

**Issue by MarchWorks** [webpack-contrib/mini-css-extract-plugin#394] opened 2019-05-13 13:28 UTC
Excuse me for posting this question here but no one will answer in stackoverflow I think that you should take a look at mini-css-ectract-plugin tag in stackoverflow from time to time.

So, I need to ensure that css being used by two or more chunks is split into a vendor chunk, i.e. style-vendor.css. if I am not mistaken we will use optimization.splitChunks but I don't have any idea of how to do so

**Comment by evilebottnawi** [comment] 2019-05-13 13:36
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You should use docs template.

And how we can help you without examples and/or minimum reproducible test repo? Maybe you don't have answer because not provide enough information.

> I need to ensure that css being used by two or more chunks is split into a vendor chunk,

Just look on your files and and their code to ensure all exists in your code.

**Closed by evilebottnawi** 2019-05-13 13:36 UTC
