### ISSUE TITLE
this[NS] is not a function

### ISSUE THREAD

**Issue by grrowl** [webpack-contrib/mini-css-extract-plugin#140] opened 2018-05-11 06:01 UTC
Logging at `mini-css-extract-plugin/dist/loader.js:147`, `NS` is `/Users/tom/Documents/projectName/node_modules/mini-css-extract-plugin/dist`. It then calls `this[NS](text)`, which fails as `this[NS]` is `undefined`.

Happens on `0.5.0` and `0.4.0` too. What gives?

**Comment by silaike** [comment] 2018-05-11 06:17
did you add `new MiniCssExtractPlugin()` in the plugins array?

**Comment by marvinhagemeister** [comment] 2018-05-11 09:04
Duplicate of #73

**Comment by evilebottnawi** [comment] 2018-05-22 10:39
@marvinhagemeister duplicate, thanks!

**Closed by evilebottnawi** 2018-05-22 10:39 UTC
