### ISSUE TITLE
Breaking JS entrypoint when extracting all css chunks into 1 file

### ISSUE THREAD

**Issue by octaharon** [webpack-contrib/mini-css-extract-plugin#147] opened 2018-05-15 16:38 UTC
Package version: 0.4.0
Node version: 6.8.0

So I've updated to webpack 4 and instantly run into [extract-text-webpack-plugin incompatibility](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701), and guys on stackoverflow insisted on switching in favor of this module.  My use case is almost exactly [as described in documentation](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file) with the difference being that there's sass-loader in the end of chain as well. All the rest is non-essential, the error is reproducable even with "zero" config. 

My project is React-based, with a set of components each having it's own scss file, required inside each component individually, including the Root component - the one which is rendered to DOM inside my entry file (say `/src/index.js`, has `require('index.scss')`).  

What happens on build stage is kinda in line with expectations - all the css got exported to `style.css` (despite it produces extra files like `style.main.js` for no obvious reason). The problem is that that my entrypoint javascript never got executed when the bundle is loaded. So there's no warnings or errors, everything compiles smoothly, the files (`main.js` and `style.css`) are delivered to the browser, but the code from `index.js` is not executed, so I just stare at a blank html template. 

In the end I switched back to `extract-text-webpack-plugin@next` cause I couldn't overcome that issue. Any ideas what causes that?

**Comment by blakedietz** [comment] 2018-05-15 22:38
I too was seeing an issue similar to this. Instead I was getting a third bundle created. For example if the bundle was named `bundle.js` I would see an output of `0.bundle.js, bundle.js, styles.css`.

**Comment by evilebottnawi** [comment] 2018-05-15 22:48
Feel free to investigate and send PR.
Don't use `extract-text-webpack-plugin@next` it is break long term cache, output very large bundle and can raise problem in runtime which very hard to find

**Comment by octaharon** [comment] 2018-05-16 07:33
Sorry, I've realized that a link to documentation was missing in my original post, edited. That's quite important for understanding the problem.

Perhaps the issue with plural output files belongs to webpack itself, since its driven by `optimization.splitChunks.cacheGroups`  config option, but the issue with "swallowing" the entrypoint of scripts is definitely coming from this plugin. If those are connected, than there's no better description 
>problems in runtime code which very hard to find and fix

Do you by chance know a repo with [the aformentioned configuration  ](https://github.com/webpack-contrib/mini-css-extract-plugin#extracting-all-css-in-a-single-file) in place? That could be a good starting point for investigation.

**Comment by dcousineau** [comment] 2018-05-17 14:07
I don't have a public repo but I finally traced my problem with production builds in webpack-4 to this issue.

In development mode my optimization stanza is:
```js
  optimization: {
    splitChunks: {
      chunks: 'all',
    },
    runtimeChunk: {
      name: 'manifest',
    },
  },
```

While in production mode I have 
```js
  optimization: {
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true
        },
      },
    },
    runtimeChunk: {
      name: 'manifest',
    },
  },
```

Production properly spits out the correct singular bundled CSS file, however my entrypoint chunk no longer executes.

**Comment by dcousineau** [comment] 2018-05-17 14:49
In attempting to reproduce a minimal problem, it appears if you don't include the outputted `styles.js` bundle generated via the cacheGroup the application won't execute at all.

**Comment by dcousineau** [comment] 2018-05-17 15:05
Please see https://github.com/dcousineau/mini-css-extract-plugin-reproduction for a demonstration of how, even though the styles.js is effectively empty it prevents the entrypoint from executing.

**Comment by octaharon** [comment] 2018-05-17 18:42
Good job with locating the repo, man! I support the idea of avoiding generating extra js files when we extract css only, that's somewhat not semantical and user-friendly at all. That configuration, as it says in the documentation, should behave pretty much the same as the extract-text-plugin in this case. Which is, by the way, works perfectly for me so far in couple with optimize-css-assets-plugin. Other option would be auto-injecting the style.js into one of entries by providing entryName or something in plugin config, declarative style, or even detecting the 'target' option of webpack itself.

**Comment by coltonw** [comment] 2018-05-23 12:05
I would like to point out that this problem is doubly bad for javascript/css libraries trying to use mini-css-extract-plugin.  Users of the library will have to not only import the library code and css, but also this generated style.js file or the library simply won't work.

**Comment by rzcoder** [comment] 2018-06-05 12:30
Can't update to webpack 4 cus this bug

**Comment by crocodilu** [comment] 2018-07-26 12:45
I have the same problem. Did someone figured this out?

**Comment by thuanmb** [comment] 2018-08-01 09:43
+1

**Comment by newmanw** [comment] 2018-08-10 20:01
+1 

Any updates?

**Comment by flylixiaolong** [comment] 2018-08-14 14:07
+1

**Comment by maapteh** [comment] 2018-08-14 16:32
For me the same, one JS entry point with CSS/SCSS in imports. As soon as i set:
`
optimization: {
        ...
        splitChunks: {
            cacheGroups: {
                styles: {
                    name: 'client',
                    test: /\.(css|scss)$/,
                    chunks: 'all',
                    enforce: true,
                    priority: 1000,
                },

`
It results in ONE css file being generated correctly but my entry JS seems to be totally wrong with only lines referring to the css parts inside the application.

**Comment by tony-landis** [comment] 2018-08-21 23:03
+1

**Comment by evilebottnawi** [comment] 2018-08-22 09:29
Please create minimum reproducible test repo

**Comment by octaharon** [comment] 2018-08-22 09:45
@evilebottnawi I suppose [that's it](#issuecomment-389899561)

**Comment by piyushmahen** [comment] 2018-08-29 06:48
@michael-ciniawsky Any timeline till when can we expect this to be fixed?

**Comment by jimmydief** [comment] 2018-09-12 20:30
Ended up concatenating the extra JS file to our entry file in a post-build step which worked.

**Comment by tony-landis** [comment] 2018-09-12 21:11
It still fundamentally antithetical to bundling - all the styles for the
entire app loading with the all.

For us, thats a 100kb js file. Vs a few KiB if it were just the styles
needed for any given page.


Anthony Landis

CTO, Founder | Anywhere.com

mobile: 206-234-1018

**Comment by fender** [comment] 2018-09-14 17:04
+1

**Comment by timothywisdom** [comment] 2018-09-19 23:44
I was able to work around this issue by using the [rename-webpack-plugin](https://github.com/Dcatfly/rename-webpack-plugin).

I configured it to search for the extra "styles" bundle (with a unique HASH) and rename it to a static "styles.bundle.js" file that I can dependably include in my entry HTML (because it always has the same name).

Here's an example
```
const RenameWebpackPlugin = require('rename-webpack-plugin')

module.exports = {
  entry: 'app.js',
  output: {
    path: __dirname + '/dist',
    filename: 'app.[chunkhash].js'
  },
  plugins: [
    new RenameWebpackPlugin({
        originNameReg: /styles\..*\.js/,
        targetName: 'styles.bundle.js'
    })
  ]
}
```

**Comment by CaptainYouz** [comment] 2018-10-04 12:41
hi! 
i have the same problem here. Any news ?

**Comment by kryptonian41** [comment] 2018-10-15 18:19
The workaround which works for me is removing, all  the instances of `chunks: "all"`.

**Comment by viljark** [comment] 2018-11-16 14:35
I am using multiple entry points so my solution may not be relevant to others.

For me including the styles chunk in the HtmlWebpackPlugin chunks list helped with the webpack bootstrap not happening on page load. Here is my code:

```
        new HtmlWebpackPlugin({
            chunks: ['styles', 'vendor', 'app'],
            inject: true,
            template: paths.appHtml,
            minify: {
                removeComments: true,
                collapseWhitespace: true,
                removeRedundantAttributes: true,
                useShortDoctype: true,
                removeEmptyAttributes: true,
                removeStyleLinkTypeAttributes: true,
                keepClosingSlash: true,
                minifyJS: true,
                minifyCSS: true,
                minifyURLs: true,
            },
        }), 
```

    optimization: {
        splitChunks: {
            cacheGroups: {
                styles: {
                    name: 'styles',
                    test: /\.css$/,
                    chunks: 'all',
                    enforce: true
                }
            }
        }
    },

**Comment by hirokiosame** [comment] 2018-12-04 19:58
I have the same problem but with Vue and I made a minimal reproduction repo for this bug: https://github.com/hirokiosame/test-build

**Comment by TerribleDev** [comment] 2018-12-07 18:48
is there any movement on this issue? IMO this is a major blocker from moving apps to webpack 4, or having webpack 4 apps do dynamic imports.

**Comment by evilebottnawi** [comment] 2018-12-07 18:52
Try to search time on this, but sorry i am very very very busy, feel free to investigate :+1:

**Comment by theshashiverma** [comment] 2019-01-17 13:37
Please help me, I have a project in laravel-vuejs and i am extracting js chunks file through my webpack.config.js and my chunks are like 0.js,1.js,2.js etc and I want to extract the chunks of css or stylesheet how can i achieve this. please help me

**Comment by PierreRambaud** [comment] 2019-02-20 15:16
Same problem here, any updates? 
Can someone have an idea about how to build css in dev environment? 

Code tu reproduce:
https://github.com/PrestaShop/PrestaShop/tree/develop/admin-dev/themes/new-theme

**Comment by zhangdongming1989** [comment] 2019-04-15 12:37
I confused about this problem for a long time, In my case two way can solve this.
1. donnot extract css in 1 file, default code split looks good.
2. just reserve the styles.js, an empty file affects little, I think.
   if use HtmlWebpackPlugin,  style.js will auto insert into html.
   if you construct html by yourself, you can do this as well

**Comment by webextensions** [comment] 2019-08-09 23:09
In my case, it turned out to be an issue in my custom plugin. So, similarly, I'm assuming that this bug may be in `html-webpack-plugin`, and probably `mini-css-extract-plugin` is working fine. In my plugin, I was not going through all the files listed under `compilation.chunks.files` which caused the behavior described in this bug.

**Comment by JonathanTR** [comment] 2019-08-23 19:24
Just a gentle bump on this thread. This is a widely used, officially designated webpack plugin and the functionality in the main README seems to have been broken for over a year. Perhaps a warning should be added to the documentation, or the relevant section should be removed.

**Comment by evilebottnawi** [comment] 2019-08-23 19:25
It is fixed for webpack@5

**Comment by privatenumber** [comment] 2019-08-23 21:09
Thanks for the update @evilebottnawi 

I'm dealing with a Vue build and it seems vue-loader is incompatible w/ Webpack 5 due to https://github.com/webpack/webpack/pull/9138, blocking me from confirming this is solved. I might investigate further when I have more time, but it seems like for Vue users we'll have to wait till Webpack 5 is stable and a compatible vue-loader is released.

**Comment by evilebottnawi** [comment] 2019-12-25 17:34
Here two problems:
1. some people forgot to add chunks on own html (yes you need include all generated chunks, even they are empty all content was extracted)
2. in some cases `html-webpack-plugin` doesn't include runtime code in html page (i think it should be already fixed, if not please open a new issue in `html-webpack-plugin`)
3. https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85 (fixed in webpack@5), it is allow to avoid empty chunks and unnecessary scripts with only extracted content

If somebody think what he/she still has a problem and it is related to this issue please open a new issue, here a lot of difference issues and it is hard to investigate.

If somebody wants to know why it is happens I can explain with comments

**Closed by evilebottnawi** 2019-12-25 17:34 UTC
Labels: priority: 3 (important), severity: 3 (broken), type: bug
