### ISSUE TITLE
Don't output empty JS files

### ISSUE THREAD

**Issue by TomS-** [webpack-contrib/mini-css-extract-plugin#151] opened 2018-05-17 10:13 UTC
I have seen people use the Extract plugin and name the file the same to prevent a useless .js file, however, naming the file the same in this instance gives the error: 
`Conflict: Multiple assets emit to the same filename main.js` 

I only want to take a CSS file and run it though autoprefix and minify, I don't need it to output a JS file.

**Comment by evilebottnawi** [comment] 2018-05-17 10:28
@TomS- can you create minimum reproducible test repo?

**Comment by TomS-** [comment] 2018-05-17 10:34
@evilebottnawi Yup, I'll set it up this evening

**Comment by TomS-** [comment] 2018-05-18 09:56
https://github.com/TomS-/minicss Sorry for the delay

**Comment by TomS-** [comment] 2018-05-21 16:39
@Tiendq I don't want Webpack to output a JS file for CSS. It seems strange to me for it to do that. At the moment I'm getting the CSS file and a JS file. I'm coming from Gulp so maybe it's just I don't understand Webpack.

**Comment by Tiendq** [comment] 2018-05-22 00:39
@TomS- I don't want it too :)

**Comment by paulmasek** [comment] 2018-06-07 04:44
+1 Mainly because it'll probably fix https://github.com/Va1/browser-sync-webpack-plugin/issues/69

**Comment by GiancarlosIO** [comment] 2018-06-13 19:38
+1

**Comment by evilebottnawi** [comment] 2018-06-15 10:22
Weppack is `js` bundle, i can not imagine why this might be necessary, please provide use case

**Comment by thewebsitedev** [comment] 2018-06-16 21:34
Same issue. I have a PHP application but I am managing assets with Webpack. With Webpack 4 & MiniCssExtractPlugin, generating CSS files is a pain at the moment. I need to directly load CSS file.

Part of my config:
```
{
    mode: "development",
        entry: {
            "admin": "./assets/admin/src/scss/theme.scss"
        },
        module: {
            rules: [
                {
                    test: /\.(sa|sc|c)ss$/,
                    use: [
	                MiniCssExtractPlugin.loader,
                        'css-loader',
                        'sass-loader'
                    ],
                },
            ]
        },
        plugins: [
            new MiniCssExtractPlugin({
                filename: "[name].css",
                chunkFilename: "[id].css"
            })
        ],
        output: {
            path: path.resolve(__dirname, 'assets/admin/dist/css')
        }
},
```

Files generated are: `admin.css` & `admin.js`.

I don't need `admin.js` file. It's useless in my case.

**Comment by bregenspan** [comment] 2018-06-18 15:17
The cause of this is probably https://github.com/webpack/webpack/issues/7300, which has been added to the Webpack 4.x milestone.

**Comment by jpdesigndev** [comment] 2018-06-21 20:11
This issue is biting me as well. Feel free to close this if this plugin can't offer an alternative. Btw, https://github.com/webpack/webpack/issues/7300 has been retagged with Webpack 5.x, so we won't likely see a fix in webpack until then.

**Comment by evilebottnawi** [comment] 2018-06-22 10:51
We search way to fix it inside plugin

**Comment by danechitoaie** [comment] 2018-06-30 14:02
Having same issue. I'm using webpack to compile both JS and SCSS and different entries (i.e. not requiring the css inside JS) and for each .css file generated I also get a .js file.

**Comment by Igloczek** [comment] 2018-07-04 01:15
Same as https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/518

**Comment by Igloczek** [comment] 2018-07-04 01:28
My temporary solution is to use this plugin - https://github.com/medfreeman/ignore-assets-webpack-plugin
Works with v4, but use deprecated methods.

**Comment by danechitoaie** [comment] 2018-07-04 07:20
I had to make my own plugin:

```
class MiniCssExtractPluginCleanup {
    apply(compiler) {
        compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
            Object.keys(compilation.assets)
                .filter(asset => {
                    return ["*/scss/**/*.js", "*/scss/**/*.js.map"].some(pattern => {
                        return minimatch(asset, pattern);
                    });
                })
                .forEach(asset => {
                    delete compilation.assets[asset];
                });

            callback();
        });
    }
}
```
It's very specific for my use case and has things hardcoded and I even have just put it directly in the webpack.config.js file (so not published on npm) but maybe it can be integrated somehow in some version directly into mini-css-extract-plugin? And made configurable with some additional options.

**Comment by Igloczek** [comment] 2018-07-10 08:45
@riccardomessineo correct me if I'm wrong, but it still generates those files, but don't add them to the html file, right?

**Comment by riccardomessineo** [comment] 2018-07-10 08:47
@Igloczek you're perfectly right. 
It does not resolve the issue, I just wanted to provide another workaround.

**Comment by fqborges** [comment] 2018-08-21 16:38
I faced the same issue of having a style only entry (css/sass/less) generating an extra .js file, and ended up creating a webpack plugin to remove the js file from the compilation.

I published it on npm as webpack-fix-style-only-entries. You can find the source code on https://github.com/fqborges/webpack-fix-style-only-entries.

:-) shamelessly promoting my package :-)

**Comment by michael-ciniawsky** [comment] 2018-08-24 13:58
> I have seen people use the Extract plugin and name the file the same to prevent a useless .js file, however, naming the file the same in this instance gives the error:
Conflict: Multiple assets emit to the same filename main.js

Use `[name]`. The empty JS File is going away (in [`webpack >= v5.0.0`](https://github.com/webpack/webpack/projects/5)), but this needs to be fixed in webpack core itself

**Comment by evilebottnawi** [comment] 2018-08-24 14:11
@michael-ciniawsky bug in plugin, still open before it was fixed in webpack

**Comment by artemkochnev** [comment] 2018-08-27 15:40
@fqborges I'm trying to use your plugin, but I'm running into a problem where the `file` is getting passed as `*` instead of the actual file path.

For example, if I add a `console.log(resources, file)`, I get a bunch of results like this: `[ '<redacted>/src/app/css/pages/Home.scss' ] '*'`

Do you know why this might be happening? The webpack docs on what gets passed for the `chunkAsset` hook are fairly light...

**Comment by fqborges** [comment] 2018-08-27 16:52
@artemkochnev would you mind to open an issue [here](https://github.com/fqborges/webpack-fix-style-only-entries/issues) to provide me more info? Relevant parts of your webpack.config, webpack version, etc.

**Comment by mojilla** [comment] 2018-11-19 10:21
@riccardomessineo 
 HtmlWebpackExcludeAssetsPlugin broke the app.

**Comment by tflori** [comment] 2018-12-25 10:49
@danechitoaie thx for the tip!

I've just created a more abstract class to do this:

```js
class Without {
    constructor(patterns) {
        this.patterns = patterns;
    }

    apply(compiler) {
        compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
            Object.keys(compilation.assets)
                .filter(asset => {
                    let match = false,
                        i = this.patterns.length
                    ;
                    while (i--) {
                        if (this.patterns[i].test(asset)) {
                            match = true;
                        }
                    }
                    return match;
                }).forEach(asset => {
                    delete compilation.assets[asset];
                });

            callback();
        });
    }
}

module.exports = {
    mode: process.env.NODE_ENV || 'development',
    resolve: {
        extensions: ['.scss', '.css']
    },
    module: {
        rules: [
            {
                test: /\.scss$/,
                use: [
                    MiniCssExtractPlugin.loader,
                    'css-loader',
                    'sass-loader',
                ],
            },
        ],
    },
    plugins: [
        new MiniCssExtractPlugin({
            filename: '[name]',
        }),
        new Without([/\.css\.js(\.map)?$/]), // just give a list with regex patterns that should be excluded
    ],
};
```

**Comment by wzc0x0** [comment] 2019-01-14 04:05
> @danechitoaie thx for the tip!
> 
> I've just created a more abstract class to do this:
> 
> class Without {
>     constructor(patterns) {
>         this.patterns = patterns;
>     }
> 
>     apply(compiler) {
>         compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
>             Object.keys(compilation.assets)
>                 .filter(asset => {
>                     let match = false,
>                         i = this.patterns.length
>                     ;
>                     while (i--) {
>                         if (this.patterns[i].test(asset)) {
>                             match = true;
>                         }
>                     }
>                     return match;
>                 }).forEach(asset => {
>                     delete compilation.assets[asset];
>                 });
> 
>             callback();
>         });
>     }
> }
> 
> module.exports = {
>     mode: process.env.NODE_ENV || 'development',
>     resolve: {
>         extensions: ['.scss', '.css']
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.scss$/,
>                 use: [
>                     MiniCssExtractPlugin.loader,
>                     'css-loader',
>                     'sass-loader',
>                 ],
>             },
>         ],
>     },
>     plugins: [
>         new MiniCssExtractPlugin({
>             filename: '[name]',
>         }),
>         new Without([/\.css\.js(\.map)?$/]), // just give a list with regex patterns that should be excluded
>     ],
> };
> ![](chrome-extension://mdcffelghikdiafnfodjlgllenhlnejl/icons/copy.png)

very well ! Thanks !

**Comment by leonexcc** [comment] 2019-04-11 08:00
I use Symfony Encore and have to fix the entrypoints too. But this should also work with a normal Webpack.

My approach to this problem:
```
class MiniCssExtractPluginCleanup {
    apply(compiler) {
        compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
            let jsFile = /\.js$/;

            compilation.entrypoints.forEach((entrypoint) => {
                entrypoint.chunks.forEach((chunk) => {
                    if (chunk.files.length > 1) {
                        let notEmptyJsModules = chunk.getModules().filter(module => {
                            return module.constructor.name === 'NormalModule'
                                && module.originalSource().source() !== '// extracted by mini-css-extract-plugin';
                        });

                        if (notEmptyJsModules.length === 0) {
                            chunk.files = chunk.files.filter(file => {
                                if (jsFile.test(file)) {
                                    delete compilation.assets[file];
                                    return false;
                                } else return true;
                            });
                        }
                    }
                });
            });

            callback()
        });
    }
}
```

and i use it with:

```
.addPlugin(new MiniCssExtractPluginCleanup(), -11)
```

**Comment by evilebottnawi** [comment] 2019-04-11 11:13
Fixed for `webpack@5`, anyway you can send a PR with fix it on `mini-css-extract-plugin` side (throw option)

**Comment by psdon** [comment] 2019-11-18 10:00
Another way: 

```
const IgnoreEmitPlugin = require('ignore-emit-webpack-plugin');
plugins: [
    new IgnoreEmitPlugin(/(?<=main_css\s*).*?(?=\s*js)/gs),
]
``

**Comment by ararename** [comment] 2019-12-04 12:53
Hello erveryone. 
After six days, for one short moment i thought i succeeded in removing 'empty' js files from the html and from the filesystem with 'html-webpack-exclude-assets-plugin' and 'ignore-emit-webpack-plugin'. 
Everything fine, links gone, empty files gone, the bootstrap js is inside of index.js, index.js is properly linked, no console error **_and all JavaScript dead_**. 

As soon as i put the line 'excludeAssets: [/app.js/, /custom.js/]' in the webpack config above in comments, everything works but i have the links to the files in the html. When i uncomment that line, the behaviour is as described above.

Some help before reaching insanity would be highly appreciated. Thank you. 

`const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('extract-css-chunks-webpack-plugin');
const HtmlWebpackExcludeAssetsPlugin = require('html-webpack-exclude-assets-plugin');
const IgnoreEmitPlugin = require('ignore-emit-webpack-plugin');

const path = require('path');
const isProd = process.env.NODE_ENV === 'production';
const outputDir = path.join(__dirname, 'build/');

module.exports = {

  entry: {
    index: path.resolve( process.cwd(), 'src', 'index.js')
  },

  mode: isProd ? 'production' : 'development',

  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index-fsc.html',
      template: 'src/index-fsc.html',
      excludeAssets: [/app.js/, /custom.js/]
    }),

    new MiniCssExtractPlugin({
      filename: isProd ? 'assets/css/[name].[hash].css' : 'assets/css/[name].css',
    }),

	new HtmlWebpackExcludeAssetsPlugin(),
	// finally, together with 'html-webpack-exclude-assets-plugin', this is useful 

	new IgnoreEmitPlugin(['app.js', 'custom.js'])
  ],

  optimization: {
     splitChunks: {
      cacheGroups: {
        app: {
          name: 'app',
          test: /app\.s?css$/,
          chunks: 'all',
          enforce: true,
        },
        custom: {
          name: 'custom',
          test: /custom\.s?css$/,
          chunks: 'all',
          enforce: true,
        }
      },
    },
  },
  
  module: {
    rules: [
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: process.env.NODE_ENV === 'development',
            },
          },
          'css-loader', 'postcss-loader', 'sass-loader',
        ],
      },  
      {
         test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
         use: [{
           loader: 'file-loader',
           options: {
             emitFile: true,
             name: '[name].[ext]',
             outputPath: 'assets/fonts/',    // where the fonts will go
             publicPath: '../fonts'       // override the default path
           }
         }]
       }
    ]
  },

  output: {
    path: outputDir,
    filename: 'assets/js/[name].js'
  },

  devServer: {
    compress: true,
    contentBase: outputDir,
    port: process.env.PORT || 8000,
    historyApiFallback: true
  }
};`

**Comment by evilebottnawi** [comment] 2019-12-04 12:55
It will be solved for webpack@5 (near future), right now please use solutions above

**Comment by ararename** [comment] 2019-12-04 13:12
Thank you for the answer but i hoped really to not get this answer. Here we have a thread discussing this very problem since 1 1/2 years, the tip to use v5 had already been given a year ago, but the discussion went on. 
As i wrote I _did_ use a solution from above, i tried _all_ of them, one worked up to the point where my _JavaScript does not work anymore_. 
I am looking for a solution for my problem.

**Comment by ararename** [comment] 2019-12-04 22:37
It turned out that not importing the scss files in my index.js but setting them as entry points in the webpack config did the job. 

Everything else was fine. I never changed this throughout my efforts to get this to work. Of course i tried setting the scss files as entry points but not once did i think of removing them from my index.js. Other solutions here might also only work well if crafted like this, i don't know, but check if they do not. 

I know some folks say that setting (s)css as an entry point should not work at all, consider it bad practice. I couldn't care less as long as i do not encounter drawbacks from that in my project (_but i am interested in what these might be_). 

And, to be honest, i have no real need to get this going this way, i am new to webpack, this is my first 'live' test which began 4 days ago. This is how i start stuff, i try to accomplish something i have in mind. That also is the reason for why there's Foundation and Bootstrap in there, i was curious. Had to get into Foundation for a job and i wanted to transfer some of my Boostrap blocks to be styled by Foundation. To do this in one file in parallel seemed interesting and now it seems to work. 
A big thank you to all the contributors to this thread, before having found it i was desperate because of this :-)

```
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require('extract-css-chunks-webpack-plugin');
const HtmlWebpackExcludeAssetsPlugin = require('html-webpack-exclude-assets-plugin');
const IgnoreEmitPlugin = require('ignore-emit-webpack-plugin');

const path = require('path');
const isProd = process.env.NODE_ENV === 'production';
const outputDir = path.join(__dirname, 'build/');

module.exports = {

  entry: {
    index: path.resolve( process.cwd(), 'src', 'index.js'),
    app: path.resolve( process.cwd(), 'scss', 'app.scss'),
    custom: path.resolve( process.cwd(), 'scss/fsc-custom', 'custom.scss')
  },

  mode: isProd ? 'production' : 'development',

  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index-fsc.html',
      template: 'src/index-fsc.html',
      excludeAssets: [/app.js/, /custom.js/]
    }),

    new MiniCssExtractPlugin({
      filename: isProd ? 'assets/css/[name].[hash].css' : 'assets/css/[name].css',
    }),

    new HtmlWebpackExcludeAssetsPlugin(),
    // finally, together with 'html-webpack-exclude-assets-plugin', this is useful 
    new IgnoreEmitPlugin(['app.js', 'custom.js'])
  ],

  optimization: {
    splitChunks: {
      cacheGroups: {
        app: {
          name: 'app',
          test: /app\.s?css$/,
          chunks: 'all',
          enforce: true,
        },
        custom: {
          name: 'custom',
          test: /custom\.s?css$/,
          chunks: 'all',
          enforce: true,
        }
      },
    },
  },
  
  module: {
    rules: [
      {
        test: /\.(sa|sc|c)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
              options: {
                hmr: process.env.NODE_ENV === 'development',
              },
          },
          'css-loader', 
          'postcss-loader', 
          'sass-loader',
        ],
      },  

      {
        test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
        use: [{
          loader: 'file-loader',
          options: {
            emitFile: true,
            name: '[name].[ext]',
            outputPath: 'assets/fonts/',
            publicPath: '../fonts'
          }
        }]
      }
    ]
  },

  output: {
    path: outputDir,
    filename: 'assets/js/[name].js'
  },

  devServer: {
    compress: true,
    contentBase: outputDir,
    port: process.env.PORT || 8000,
    historyApiFallback: true
  }
};
```

**Comment by evilebottnawi** [comment] 2019-12-25 14:17
Close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/85

**Closed by evilebottnawi** 2019-12-25 14:17 UTC

**Comment by grahamsutton** [comment] 2020-09-02 00:43
Just another idea, in case you know which directory you want to remove the useless JS file from and your webpack command is aliased as an npm run command then you can just issue a wildcard delete for anything that ends with a `.js` extension in that directory. Not a perfect solution, but satisfactory.

Example:

In `package.json`

```
{
  ...
  "scripts": {
    "build": "node_modules/.bin/webpack && rm -Rf ./dist/css/*.js"
  }
}
```

then

```sh
$ npm run build
```

**Comment by Bilge** [comment] 2020-12-21 19:51
v5 is here and it has changed absolutely nothing.

**Comment by zhuzhuyule** [comment] 2021-01-13 13:35
```
// webpack.config.js
{
  optimization: {
      splitChunks: {
        cacheGroups: {
          styles: {
            ...
            type: 'css/mini-extract',
            ...
          },
        },
      },
    },
}
```
I added the `type: 'css/mini-extract',` config. And then resolved the problem!

**Comment by koga73** [comment] 2021-02-09 22:42
> ```
> // webpack.config.js
> {
>   optimization: {
>       splitChunks: {
>         cacheGroups: {
>           styles: {
>             ...
>             type: 'css/mini-extract',
>             ...
>           },
>         },
>       },
>     },
> }
> ```
> 
> I added the `type: 'css/mini-extract',` config. And then resolved the problem!

This doesn't work, at least not with WebPack 4. How does it work for you?

**Comment by alexb-uk** [comment] 2021-03-26 12:37
If it helps anyone I used the plugin [remove-files-webpack-plugin](https://www.npmjs.com/package/remove-files-webpack-plugin), just need to change `folder` to match your project structure:

```javascript
new RemovePlugin({
  /**
   * After compilation permanently remove empty JS files created from CSS entries.
   */
  after: {
    test: [
      {
        folder: 'dist/public/css',
        method: (absoluteItemPath) => {
          return new RegExp(/\.js$/, 'm').test(absoluteItemPath);
        },
      }
    ]
  }
}),
```

**Comment by Ihor139** [comment] 2024-04-24 07:06
> @danechitoaie thx for the tip!
> 
> I've just created a more abstract class to do this:
> 
> ```js
> class Without {
>     constructor(patterns) {
>         this.patterns = patterns;
>     }
> 
>     apply(compiler) {
>         compiler.hooks.emit.tapAsync("MiniCssExtractPluginCleanup", (compilation, callback) => {
>             Object.keys(compilation.assets)
>                 .filter(asset => {
>                     let match = false,
>                         i = this.patterns.length
>                     ;
>                     while (i--) {
>                         if (this.patterns[i].test(asset)) {
>                             match = true;
>                         }
>                     }
>                     return match;
>                 }).forEach(asset => {
>                     delete compilation.assets[asset];
>                 });
> 
>             callback();
>         });
>     }
> }
> 
> module.exports = {
>     mode: process.env.NODE_ENV || 'development',
>     resolve: {
>         extensions: ['.scss', '.css']
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.scss$/,
>                 use: [
>                     MiniCssExtractPlugin.loader,
>                     'css-loader',
>                     'sass-loader',
>                 ],
>             },
>         ],
>     },
>     plugins: [
>         new MiniCssExtractPlugin({
>             filename: '[name]',
>         }),
>         new Without([/\.css\.js(\.map)?$/]), // just give a list with regex patterns that should be excluded
>     ],
> };
> ```

Thank you very much for your help, I have tried several times to compile for separate js and css files and always had problems, but you helped a lot with your code. Good to you!!!!!
