### ISSUE TITLE
Breaking change with import via CommonJS in `2.5.0`

### ISSUE THREAD

**Issue by Cherry** [webpack-contrib/mini-css-extract-plugin#896] opened 2022-01-14 17:57 UTC
### Bug report

Since 2.5.0, importing via CommonJS no longer matches what it did in the past, or what is shown in the documentation.
```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
console.log(MiniCssExtractPlugin);
```
```
{
  default: [class MiniCssExtractPlugin] {
    loader: 'E:\\GitHub\\website\\node_modules\\mini-css-extract-plugin\\dist\\loader.js'
  },
  pluginName: 'mini-css-extract-plugin',
  pluginSymbol: Symbol(mini-css-extract-plugin)
}
```

### Actual Behavior
```js
new MiniCssExtractPlugin()
```
This throws a `TypeError: MiniCssExtractPlugin is not a constructor` when attempting to use in the documented way. Using the exported `.default` works fine, but I assume is not the intended behaviour.

### Expected Behavior

It should behave exactly as it did in 2.4.6 and below.  This is likely the result of the change to the `main` export in https://github.com/webpack-contrib/mini-css-extract-plugin/commit/5b5654c9847a615555660d79245b857536f72124#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L14, and the deletion of the `src/cjs.js` script and its build.

Previously in 2.4.6:
```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
console.log(MiniCssExtractPlugin);
```
```
[class MiniCssExtractPlugin] {
  loader: 'E:\\GitHub\\website\\node_modules\\mini-css-extract-plugin\\dist\\loader.js'
}
```

**Comment by RatherLogical** [comment] 2022-01-14 17:59
A temporary workaround is this usage:

`const MiniCssExtractPlugin = require("mini-css-extract-plugin").default;`

**Comment by pgnd** [comment] 2022-01-14 20:24
@RatherLogical 

> A temporary workaround is this usage:
> 
> `const MiniCssExtractPlugin = require("mini-css-extract-plugin").default;`

works for `require` usage. thx o/

how's that default get correctly tacked on for `import`, instead?, e.g. @
```
cat webpack.parts.mjs

	...
	import CssMinimizerPlugin from 'css-minimizer-webpack-plugin';
	...
	const loadSCSS = ({ filename, chunkFilename, includePaths, minimize }) => {
395		const plugin = new MiniCssExtractPlugin({
			filename,
			chunkFilename,
		});
		return {
			module: {
				rules: [
					{
						test: /\.s?[ac]ss$/i,
	...
```

**Comment by Genenenenaam** [comment] 2022-01-14 20:27
> A temporary workaround is this usage:
> 
> `const MiniCssExtractPlugin = require("mini-css-extract-plugin").default;`

If i apply this workaround and perform the webpack build command to create a production build, i get this error:
```
[webpack-cli] ModuleNotFoundError: Module not found: Error: path argument is not a string
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/Compilation.js:2011:28
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/NormalModuleFactory.js:795:13
    at eval (eval at create (/Users/XXX/Sites/webPacker/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/NormalModuleFactory.js:275:22
    at eval (eval at create (/Users/XXX/Sites/webPacker/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/NormalModuleFactory.js:538:15
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/NormalModuleFactory.js:124:11
    at /Users/XXX/Sites/webPacker/node_modules/webpack/lib/NormalModuleFactory.js:609:8
    at /Users/XXX/Sites/webPacker/node_modules/neo-async/async.js:2830:7
    at done (/Users/XXX/Sites/webPacker/node_modules/neo-async/async.js:2925:13)
```
Running webpack in `development` mode does seem to work.

My workaround was to change the package.json version from: 
`"mini-css-extract-plugin": "^2.4.5"` to `"mini-css-extract-plugin": "~2.4.5"` (replaced ^ symbol with ~)

**Comment by pencil** [comment] 2022-01-14 21:39
For anyone else running into this with an app created via `create-react-app`, add this to your `package.json`:
```
  "resolutions": {
    "mini-css-extract-plugin": "~2.4.5"
  }
```

**Comment by gguynn** [comment] 2022-01-14 21:50
I've tried the resolutions method (npm), and it usually works in every situation.  But not here.  I had to take a different approach for our deployments to succeed.

> package.json (added node preinstallHotfix)
```
  "scripts": {
    "preinstall": "npx npm-force-resolutions && node preinstallHotfix",
 ```

> preinstallHotfix.js
```
// temp patch breaking change
// https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896

const fs = require("fs")

const file = "./node_modules/react-scripts/config/webpack.config.js"

console.log(
  "Applying hotfix for https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896..."
)

fs.readFile(file, "utf8", function (err, data) {
  if (err) {
    return console.log(err)
  }
  const result = data.replace(
    /require('mini-css-extract-plugin');/g,
    "require('mini-css-extract-plugin').default;"
  )

  fs.writeFile(file, result, "utf8", function (err) {
    if (err) return console.log(err)
  })
})
```

**Comment by jsg2021** [comment] 2022-01-14 22:39
It looks like the export signature got double applied? with a `default.default`

its also broken with importing from an mjs file... (node 17)
```js
import * as test from 'mini-css-extract-plugin'
console.log(test);
```
>
```
[Module: null prototype] {
   __esModule: true,
   default: {
     default: [class MiniCssExtractPlugin] {
       loader: '/home/jonathan/Workspace/wb/wb-hub/node_modules/mini-css-extract-plugin/dist/loader.js'
     },
     pluginName: 'mini-css-extract-plugin',
     pluginSymbol: Symbol(mini-css-extract-plugin)
   },
   pluginName: 'mini-css-extract-plugin',
   pluginSymbol: Symbol(mini-css-extract-plugin)
 }
```

**Comment by jonshipman** [comment] 2022-01-14 22:53
Breaks @wordpress/scripts

**Comment by AviVahl** [comment] 2022-01-14 23:35
@alexander-akait this regressed with https://github.com/webpack-contrib/mini-css-extract-plugin/pull/895
removing the cjs entry is a breaking change, as it changes the shape of the library completely.

**Comment by streetguy911** [comment] 2022-01-14 23:47
> @alexander-akait this regressed with #895 removing the cjs entry is a breaking change, as it changes the shape of the library completely.

yeah, such change definitely should not come with minor version update

**Comment by jsg2021** [comment] 2022-01-15 00:29
> > @alexander-akait this regressed with #895 removing the cjs entry is a breaking change, as it changes the shape of the library completely.
> 
> 
> 
> yeah, such change definitely should not come with minor version update

Guys, it looks like a minor mistake. They did not intend to change the shape of the module.

**Comment by bencresty** [comment] 2022-01-15 10:52
Confirmed; same issue here; 2.5.0 breaks existing working webpack config:

![image](https://user-images.githubusercontent.com/69322733/149619058-e0a8360a-ee4e-4b07-be2d-f53cfc7bf623.png)

Going back to 2.4.5 now until this is fixed.

**Comment by drewwills** [comment] 2022-01-15 11:46
We also had this issue and pegged the version at `2.4.7` to solve it.

**Comment by malqqin** [comment] 2022-01-16 03:46
just a start at the beginning of webpack@5
 package.json
```
  "devDependencies": {
    "mini-css-extract-plugin": "^2.5.0"
  }
```
  webpack.config.js
`  const MiniCssExtractPlugin = require("mini-css-extract-plugin").default;` //that is ok.

**Comment by gziolo** [comment] 2022-01-16 07:05
> Breaks @wordpress/scripts

More details in https://github.com/WordPress/gutenberg/issues/37992.

It would be great to publish 2.5.1 with the change impacting CommonJS usage reverted and then publish 3.0.0 to ensure that so many projects don’t have to pin previous versions.

**Comment by dfblhmm** [comment] 2022-01-16 07:29
I think it should not change the module type in the minor version

**Comment by ImanMh** [comment] 2022-01-16 07:43
This is causing projects such as CRA to break. You should have bumped up the main version for such changes or not make such change at all.

**Comment by AviVahl** [comment] 2022-01-16 12:33
@sokra FYI

**Comment by snitin315** [comment] 2022-01-16 12:39
We will fix it soon.

**Comment by ImanMh** [comment] 2022-01-16 19:19
@snitin315 did you published 5 over 4.2.5? cause now I see that even installing 2.4.5 manually does not work anymore for CRA.

**Comment by streetguy911** [comment] 2022-01-16 19:49
> 

this is because CRA react-scripts contains mini-css-extract-plugin@^2.4.5 itself

**Comment by xavierfoucrier** [comment] 2022-01-16 23:38
Probably a minor mistake. Should be fixed this week, and fast as usual :+1:

**Comment by cenfun** [comment] 2022-01-17 06:31
same issue
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
...
new MiniCssExtractPlugin({
^
TypeError: MiniCssExtractPlugin is not a constructor
...

**Comment by dngconsulting** [comment] 2022-01-17 07:06
Any status on the fix ? A lot of CI servers install react native CRA and npm run build their apps. All broken now...

**Comment by andershagbard** [comment] 2022-01-17 10:15
This version is also creating a loop in the CSS builds in my webpack config, when using the watch command.

**Comment by dilyanpalauzov** [comment] 2022-01-17 10:31
19 persons are listening here to get update, once the problem is fixed.

Please refrain from all “Me too” comments, as these 19 persons are not interested in them.  Please discuss only proposed fixed.

**Comment by alexander-akait** [comment] 2022-01-17 11:14
WIP, sorry for bug, my mistake

**Comment by xavierfoucrier** [comment] 2022-01-17 11:19
Guys, it's open source. Relax and be patient. Take some coffee :coffee: :v: 
Thanks @alexander-akait for your work :sunglasses:

**Closed** 2022-01-17 12:12 UTC

**Comment by alexander-akait** [comment] 2022-01-17 12:15
Please try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v2.5.1, yes, it was bug, we should not export `default`, it was because i forgot to change `export` on `module.exports` when added types

**Comment by alexander-akait** [comment] 2022-01-17 12:18
And please do not use `default` workaround, it can lead to more problems, just update to v2.5.1 and return original setup

**Comment by martinpitt** [comment] 2022-01-17 12:41
Many thanks @alexander-akait for the fast fix, and for providing one of these pieces which holds the internet together! :star:

**Comment by silkfire** [comment] 2022-01-17 14:05
> Many thanks @alexander-akait for the fast fix, and for providing one of these pieces which holds the internet together! ⭐

I find it quite scary that the "internet" is so dependent on a fix from a handful of contributors who have access to one very popular repository.

https://thenewstack.io/is-open-source-really-free-if-we-arent-allowed-to-break-it/

**Comment by alexander-akait** [comment] 2022-01-17 14:30
Yeah, according to npm statistics, I own about 8 packages of 100 top (it is very important for all JS community), so I assigned 2 independent (and trusted) persons in the event that I cannot continue support for reasons beyond my control

**Comment by gguynn** [comment] 2022-01-17 18:41
Thanks @alexander-akait

**Comment by zubin-madon** [comment] 2022-01-18 17:43
> A temporary workaround is this usage:
> 
> `const MiniCssExtractPlugin = require("mini-css-extract-plugin").default;`

I did the above, however now I am facing a problem further down into the code.
`loader: MiniCssExtractPlugin.default.loader,`
TypeError: Cannot read property 'default' of undefined

**Comment by alexander-akait** [comment] 2022-01-18 17:59
@zubin-madon Please remove `default` https://github.com/webpack-contrib/mini-css-extract-plugin/issues/896#issuecomment-1014461012

**Comment by zubin-madon** [comment] 2022-01-18 19:11
> 

This worked for me. I replace ^ with ~
Tyvm.
