### ISSUE TITLE
Webpack 5.beta.11: HMR error  Cannot read property 'getModuleIndex2' of undefined

### ISSUE THREAD

**Issue by Levdbas** [webpack-contrib/mini-css-extract-plugin#487] opened 2019-12-29 15:25 UTC
- Operating System:
- Node Version: 13.3
- NPM Version: 6.13.1
- webpack Version: 5.0.0-beta.11
- mini-css-extract-plugin Version: 0.9

## HMR code

```js
{
                        loader: MiniCssExtractPlugin.loader,
                        options: {
                            publicPath: '../',
                            sourceMap: CreateSourceMap,
                            hmr: watchMode,
                            reloadAll: true,
                        },
                    },
```

### Expected Behavior

1. Run webpack in watchmode with HMR
2. compile css, no issue
3. rerun, no issue :)

### Actual Behavior

1. Run webpack in watchmode with HMR
2. compile css, no issue
3. rerun, issue :(

`TypeError: Cannot read property 'getModuleIndex2' of undefined
    at MiniCssExtractPlugin.renderContentAsset ([...]/node_modules/mini-css-extract-plugin/dist/index.js:301:27)`

It seems that getModuleIndex2 is deprecated in webpack 5. I don't know if this plugin is already compatible. If needed I can create a repo with minimal code.

**Comment by evilebottnawi** [comment] 2019-12-30 10:56
Can you create reproducible test repo?

**Comment by Levdbas** [comment] 2019-12-30 20:07
Hi @evilebottnawi , I've tried to make the repo as small as possible: https://github.com/Levdbas/webpack-mini-css-extract-plugin-hmr-error

While doing that I found out that removing ` new webpack.HotModuleReplacementPlugin(),` from the webpack.config.js fixes the issue. But disables the HMR altogether. I have too little insight on how the HMR actually works in the background to pinpoint where the problem lies. Is it the ` webpack.HotModuleReplacementPlugin()` or something with `mini-css-extract-plugin`. I am kind of at a stale here. Please let me know if I can help you pintpoint this any further.

**Comment by fivethreeo** [comment] 2020-02-29 16:38
getModuleIndex2 is deprecated but still exists, this is a problem with groupsIterable being a empty array

**Comment by fivethreeo** [comment] 2020-03-01 08:50
Seems like HotUpdateChunk has no ChunkGroups to me. Can we just skip some checks if it is a HotUpdateChunk. Not sure the ChunkGroups matter in a hot update.

**Comment by infime** [comment] 2020-03-02 14:30
@fivethreeo I would be happy to test any fix you are able to come up with. :smile:

**Comment by fivethreeo** [comment] 2020-03-02 15:08
Error seems to be gone in webpack@beta.13 but there are new errors about ordering

**Comment by fivethreeo** [comment] 2020-03-02 15:35
Strange, unable to reproduce bug now, even in beta.11

**Comment by infime** [comment] 2020-03-02 15:47
I am fairly certain I saw the exact same issue with hmr but quickly went
back to v4.

**Comment by fivethreeo** [comment] 2020-03-02 16:19
Me too, quite sure I saw it

**Comment by fivethreeo** [comment] 2020-03-02 20:35
https://github.com/fivethreeo/webpack-mini-css-extract-plugin-hmr-error/runs/480649121?check_suite_focus=true

But, working fine here, see the run above

**Comment by infime** [comment] 2020-03-03 18:38
Still seeing this with webpack@5.0.0-beta.13 and webpack-dev-server It occurs when changing css and expecting a hot reload:

```
/home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:301
    if (typeof chunkGroup.getModuleIndex2 === 'function') {
                          ^

TypeError: Cannot read property 'getModuleIndex2' of undefined
    at MiniCssExtractPlugin.renderContentAsset (/home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:301:27)
    at Object.render (/home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:164:32)
    at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/HotModuleReplacementPlugin.js:363:32
    at Hook.eval [as call] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
    ```
    at Hook.CALL_DELEGATE [as _call] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:14:14)
    at cont (/home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1643:40)
    at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1704:8
    at /home/u/dev/proj/frontend/.yarn/cache/neo-async-npm-2.6.1-96bc443be6-2.zip/node_modules/neo-async/async.js:2830:7
    at Object.each (/home/u/dev/proj/frontend/.yarn/cache/neo-async-npm-2.6.1-96bc443be6-2.zip/node_modules/neo-async/async.js:2850:39)
    at Compilation.createChunkAssets (/home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:2377:12)
    at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1700:12
    at Hook.eval [as callAsync] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:18:14)
    at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1582:36
    at Hook.eval [as callAsync] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:18:14)
```

**Comment by sokra** [comment] 2020-03-04 10:21
This should be fixed in webpack/webpack

**Comment by fivethreeo** [comment] 2020-03-05 02:29
> Still seeing this with webpack@5.0.0-beta.13 and webpack-dev-server It occurs when changing css and expecting a hot reload:
> 
> ```
> /home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:301
>     if (typeof chunkGroup.getModuleIndex2 === 'function') {
>                           ^
> 
> TypeError: Cannot read property 'getModuleIndex2' of undefined
>     at MiniCssExtractPlugin.renderContentAsset (/home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:301:27)
>     at Object.render (/home/u/dev/proj/frontend/.yarn/$$virtual/mini-css-extract-plugin-virtual-d418d84eb1/0/cache/mini-css-extract-plugin-npm-0.9.0-f8c8899095-2.zip/node_modules/mini-css-extract-plugin/dist/index.js:164:32)
>     at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/HotModuleReplacementPlugin.js:363:32
>     at Hook.eval [as call] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:1)
>     ```
>     at Hook.CALL_DELEGATE [as _call] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:14:14)
>     at cont (/home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1643:40)
>     at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1704:8
>     at /home/u/dev/proj/frontend/.yarn/cache/neo-async-npm-2.6.1-96bc443be6-2.zip/node_modules/neo-async/async.js:2830:7
>     at Object.each (/home/u/dev/proj/frontend/.yarn/cache/neo-async-npm-2.6.1-96bc443be6-2.zip/node_modules/neo-async/async.js:2850:39)
>     at Compilation.createChunkAssets (/home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:2377:12)
>     at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1700:12
>     at Hook.eval [as callAsync] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:18:14)
>     at /home/u/dev/proj/frontend/.yarn/cache/webpack-npm-5.0.0-beta.13-3ca4e42afa-2.zip/node_modules/webpack/lib/Compilation.js:1582:36
>     at Hook.eval [as callAsync] (eval at create (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
>     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/u/dev/proj/frontend/.yarn/cache/tapable-npm-2.0.0-beta.9-f864df88fb-2.zip/node_modules/tapable/lib/Hook.js:18:14)
> ```

Is this using my example? If not can you post your webpack config?

**Comment by fivethreeo** [comment] 2020-03-06 17:50
I tried with webpack-dev-server too, no such error here.

https://github.com/fivethreeo/webpack-mini-css-extract-plugin-hmr-error/runs/490838699?check_suite_focus=true

Check out my example and see if it runs locally for you.

git clone https://github.com/fivethreeo/webpack-mini-css-extract-plugin-hmr-error.git
cd webpack-mini-css-extract-plugin-hmr-error
NODE_ENV=development yarn install
yarn run devserver

**Comment by infime** [comment] 2020-03-17 11:42
@fivethreeo I pulled your example repo and I am able to reproduce by starting the dev server and then making a change to test.scss

**Comment by fivethreeo** [comment] 2020-03-17 13:57
Ok, reinstalled node modules and can confirm now.

**Comment by fivethreeo** [comment] 2020-03-17 16:22
https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L414

In this line the destructuring does not yield a ChunkGroup even though the set is not empty.

This chunkGroup is only needed to fall back if we are below webpack 4.

of in

https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L416

We change to

```js
if (typeof chunkGroup === 'undefined' || typeof chunkGroup.getModuleIndex2 === 'function')
```

We get more interesting errors :)

**Comment by fivethreeo** [comment] 2020-03-19 09:13
Looking at razzle, I see they just use mini-css-extract-plugin when building production css. Just style-loader is used in development with hmr.

**Comment by allocenx** [comment] 2020-04-12 09:12
So, is there any fix for this yet? I can't get this work at all, on beta 13 of the webpack 5. Is there a workaround until a fix is out??

**Comment by fivethreeo** [comment] 2020-04-13 22:21
No fix yet, but just don't use this with hmr in dev. Just use the style loader instead when developing and just use this plugin when building the production build.

**Comment by lhz516** [comment] 2020-05-16 05:54
Exact same issue here. Let share some debug experience. Hopefully it can give the author some insights to fix.

WhenI changed something and saving the stylesheet. It triggered `renderContentAsset` twice. The first time is normal - `chunk.groupsIterable` is a `Set` with one element; but the second time `chunk.groupsIterable` is an empty `Set` which causes the uncaught error

![image](https://user-images.githubusercontent.com/9879279/82112025-40b9cf00-96fe-11ea-91f7-f11f40b711a9.png)

**Comment by kamilic** [comment] 2020-05-18 06:37
still same issues in `webpack@5.0.0-beta.15`

**Comment by slightlyfaulty** [comment] 2020-06-22 01:22
Still same issue in `webpack@5.0.0-beta.18`.

This is a show-stopper bug completely preventing HMR with MiniCssExtractPlugin in Webpack 5. Please give this some attention 🙏

**Comment by vankop** [comment] 2020-06-30 07:30
@evilebottnawi I will take a look on this, any blockers?

**Comment by evilebottnawi** [comment] 2020-06-30 11:12
@vankop go ahead, no blokers

**Comment by osvaldovega** [comment] 2020-08-02 22:06
- Operating System: MacOS Catalina
- Node Version: v13.140
- NPM Version: v6.14.15
- webpack Version: v5.0.0-beta.22
- mini-css-extract-plugin Version: v0.9.0

I have the same problem with Webpack `5-beta.22`, probably you guys already know this but look like the problem, is related the HMR for (CSS|SCSS) files using the `mini-css-extract-plugin`, if I use the following configuration for CSS files

```
{
  test: /\.css$/,
  use: [MiniCssExtractPlugin.loader, 'css-loader'],
}
```

I get the following error.

```
✖ ｢wdm｣: caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'getModuleIndex2' of undefined
    at MiniCssExtractPlugin.renderContentAsset (/Users/ovega/Desktop/javascript/node_modules/mini-css-extract-plugin/dist/index.js:301:27)
    at Object.render (/Users/ovega/Desktop/javascript/node_modules/mini-css-extract-plugin/dist/index.js:164:32)
    at /Users/ovega/Desktop/javascript/node_modules/webpack/lib/HotModuleReplacementPlugin.js:464:32
    at Hook.eval [as callAsync] (eval at create (/Users/ovega/Desktop/javascript/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ovega/Desktop/javascript/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/Users/ovega/Desktop/javascript/node_modules/webpack/lib/Compilation.js:1917:32)
    at /Users/ovega/Desktop/javascript/node_modules/webpack/lib/Compilation.js:1960:8
    at /Users/ovega/Desktop/javascript/node_modules/neo-async/async.js:2830:7
    at Object.each (/Users/ovega/Desktop/javascript/node_modules/neo-async/async.js:2850:39)
    at Compilation.createChunkAssets (/Users/ovega/Desktop/javascript/node_modules/webpack/lib/Compilation.js:2681:12)
```

But if I replace in the Webpack configuration the `mini-css-extract-plugin` for `style-loader` everything works fine again.

```
{
  test: /\.css$/,
  use: ['style-loader', 'css-loader'],
}
```

Now when I run the application for the first time everything loads properly, no errors, and the styles file loads ok, but as soon I make the minimum change in the CSS files after reloads is when I get the error message.

I don't know exactly what changes in `Webpack` and the `mini-css-extract-plugin`, but looks like using this plugin causes the problem.

NOTE: 
As I saw in this thread I tried disabling the `new webpack.HotModuleReplacementPlugin()` as someone mentioned this could fixed the problem, however in my case removing this plugin didn't affect at all the result, I still got the error.

**Comment by aebrewes** [comment] 2020-08-12 05:35
I have to ask. Is there any way to fix it in the mini-css-extract plugin or do we have to wait for webpack?

**Comment by evilebottnawi** [comment] 2020-08-12 10:36
fix will be in near future

**Comment by evilebottnawi** [comment] 2020-08-27 16:20
@vankop Can you test https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v0.11.0?

**Comment by slightlyfaulty** [comment] 2020-08-27 18:31
I tried out the update, but seeing a different error now. Hope it helps.

```
TypeError: Cannot read property 'getModulePostOrderIndex' of undefined
    at MiniCssExtractPlugin.renderContentAsset (/node_modules/mini-css-extract-plugin/dist/index.js:384:26)
    at Object.render (/node_modules/mini-css-extract-plugin/dist/index.js:225:34)
    at /node_modules/webpack/lib/HotModuleReplacementPlugin.js:488:32
    at Hook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/node_modules/tapable/lib/Hook.js:18:14)
    at cont (/node_modules/webpack/lib/Compilation.js:1975:33)
    at /node_modules/webpack/lib/Compilation.js:2013:9
    at /node_modules/neo-async/async.js:2830:7
    at Object.each (/node_modules/neo-async/async.js:2850:39)
    at Compilation.createChunkAssets (/node_modules/webpack/lib/Compilation.js:2969:12)
```

Using the latest `webpack@5.0.0-beta.28`

**Comment by evilebottnawi** [comment] 2020-08-28 11:21
@slightlyfaulty Big thanks for testing, WIP on compatibility more

**Comment by evilebottnawi** [comment] 2020-08-28 11:22
@slightlyfaulty it is weird what we have HMR tests and nothing is broken, maybe you can provide simple reproducible test repo?

**Comment by Levdbas** [comment] 2020-08-28 12:50
@slightlyfaulty , are you using weback-dev-middleware as well? Might have something to do with that. I've ran into the same issue after updating my initial test repository: https://github.com/Levdbas/webpack-mini-css-extract-plugin-hmr-error from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/487#issuecomment-569782241_ . @evilebottnawi minimal test repo is updated.

**Comment by evilebottnawi** [comment] 2020-08-28 13:21
@Levdbas thanks, I will look at this in near future

**Comment by slightlyfaulty** [comment] 2020-08-28 13:29
@Levdbas Yes that must be it. I wasn't aware webpack HMR was possible without it.

**Comment by slightlyfaulty** [comment] 2020-08-28 14:25
@evilebottnawi [slightlyfaulty/webpack-mcep-repro-487](https://github.com/slightlyfaulty/webpack-mcep-repro-487)

1) `yarn start`
2) Change `src/index.css`

**Comment by DalimTeam** [comment] 2020-09-17 23:17
Nothing changes? Still not working. 
`(node:8118) [DEP_WEBPACK_MODULE_NEED_REBUILD] DeprecationWarning: Module.needRebuild is deprecated in favor of Module.needBuild
✖ ｢wdm｣: HookWebpackError: Cannot read property 'getModuleIndex2' of undefined`

**Comment by fivethreeo** [comment] 2020-09-17 23:57
This isssue changed from a missing getModuleIndex2 on undefined to a missing getModulePostOrderIndex on undefined, so nothing changed. So the error occurs before.

**Comment by evilebottnawi** [comment] 2020-10-02 13:32
Please try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v0.11.3, if you faced with issue(s)/problems, please open new issue with simple reproducible test repo, thanks for using webpack

**Closed by evilebottnawi** 2020-10-02 13:32 UTC
