### ISSUE TITLE
publicPath not doing anything

### ISSUE THREAD

**Issue by HoldYourWaffle** [webpack-contrib/mini-css-extract-plugin#403] opened 2019-05-25 13:10 UTC
This might be related to #222.

* Operating System: Windows 10
* Node Version: v10.12.0
* NPM Version: v6.9.0
* webpack Version: v4.32.2
* mini-css-extract-plugin Version: v0.6.0

### Expected Behavior
`publicPath` should overwrite the output directory specified in `output.path`

### Actual Behavior
Using `publicPath` doesn't seem to do anything. If it's defined as a function it *does* get called, but the return value is never used.

### Code

```js
module: {
	rules: [
		{
			test: /\.tsx?$/,
			use: 'ts-loader',
			exclude: /node_modules/
		},
		
		{
			test: /\.s?css$/,
			use: [
				{
					loader: MiniCssExtractPlugin.loader,
					options: {
						publicPath: 'any/path/absolute/or/relative'
					}
				},
				'css-loader'
			]
		}
	]
}
```
[Full config](https://gist.github.com/HoldYourWaffle/d89f26e43978f9ab22960aa40c834988)

### How Do We Reproduce?
By using the configuration above.

**Comment by evilebottnawi** [comment] 2019-05-27 09:55
Please create minimum reproducible test repo, i think you have invalid configuratiob

**Comment by Noitidart** [comment] 2019-07-13 02:32
I also have this issue my code is here:

```
{
    mode: process.env.NODE_ENV === 'production' ? 'production' : 'development',
    devtool: process.env.NODE_ENV === 'production' ? undefined : 'eval-source-map',
    entry: './assets/js/index.js',
    output:
    {
        filename: 'index.bundle.js',
        path: path.resolve(__dirname, '../.tmp/public/js'),
        publicPath: '/js/'
    },
    plugins: [
        new MiniCssExtractPlugin(
        {
            filename: 'main.bundle.css'
        }),
    ],
    module:
    {
        rules: [
        {
            test: /\.js$/,
            exclude: /node_modules|dependencies/,
            loader: 'babel-loader'
        },
        {
            test: /\.css$/,
            exclude: /node_modules/,
            use: [
            {
                loader: MiniCssExtractPlugin.loader
                options:
                {
                    publicPath: '/css/'
                }
            }, 'css-loader']
        },
        {
            test: /\.less$/,
            exclude: /node_modules/,
            use: [
            {
                loader: MiniCssExtractPlugin.loader
                options:
                {
                    publicPath: '/css/'
                }
            }, 'css-loader', 'less-loader']
        }]
    }
},
```

Any advice would be awesome.

**Comment by Ventore** [comment] 2019-07-25 08:18
Have the same issue! When **file-loader** has specified puplicPath option, publicPath in **MiniCssExtractPlugin.loader** does nothing, when I remove file-loader's publicPath everything works fine

**Comment by evilebottnawi** [comment] 2019-07-25 08:20
Please create minimum reproducible test repo

**Comment by TheBoroer** [comment] 2019-09-07 19:58
I just had the same problem and found a fix when I came across this [comment](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/137#issuecomment-387717213)

The readme says `Options similar to the same options in webpackOptions.output` which makes us believe we can have similar options (path, publicPath, etc.)....which is WRONG.

To get it to work, just add the relative path in the `filenam` option like this:

```
new MiniCssExtractPlugin({
    filename: 'public/css/main.bundle.css'
}),
```

**Comment by Noitidart** [comment] 2019-09-07 20:22
Thank you! I will try and let you know how it goes!

**Comment by bitfella** [comment] 2019-09-19 10:52
Any update on this? publicPath is useless right now. It is executed, but its value is never used.

**Comment by iDenisM** [comment] 2019-09-19 12:00
Also trying to use 'publicPath' but it doesn't work right now

**Comment by mbejda** [comment] 2019-09-25 14:36
Not working for me either.

**Comment by tylerrrkd** [comment] 2019-09-29 02:26
My version is 0.8.0 and it's the latest one. [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin#publicpath) shows that `publicPath` property, but it doesn't work for me either.

**Comment by tylerrrkd** [comment] 2019-09-29 07:28
Ooops, my problem was solved accidentally... I found that my  `router` missing a property named `path` (works like `ouput.publicPath` I think). After then, I try to change the value of `loaders.options.publicPath` and it works!

**Comment by Noitidart** [comment] 2019-09-29 13:29
Wow that's interesting, thanks for sharing. I still couldn't get it to work.

**Comment by alessiofachechi** [comment] 2019-10-01 23:26
Despite I landed here for the same reason described by @HoldYourWaffle, now that I've better read the docs of both `MiniCssExtractPlugin` and `webpack.output` I think that there's a misunderstanding about the expected behavior of the plugin's `publicPath` option.

What we're currently expecting from the `publicPath` option is what in the case of `webpack.output` is done by `path`. But `webpack.output` allows for `publicPath` too. According to the docs the former is [the output directory as an absolute path](https://webpack.js.org/configuration/output/#outputpath), while the latter [specifies the public URL of the output directory when referenced in a browser](https://webpack.js.org/configuration/output/#outputpublicpath).

In a few words what we wanted here is `path`, not `publicPath`. And the `path` behavior can be achieved through the plugin `filename` option, as already said in some comments above.

```js
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  plugins: [
    new MiniCssExtractPlugin({
      // path relative to the output.path
      // e.g. assets/style/main.css => dist/assets/style/main.css
      filename: 'assets/style/[name].css',
    })
  ],
```

**Comment by woutrbe** [comment] 2019-10-20 08:41
Thanks for the explanation @alessiofachechi, it took my quite a while to figure this out.
The documentation actually says `// Options similar to the same options in webpackOptions.output`, however it looks like `path` isn't supported. Using `filename` to also set the output directory isn't very clear. 

Hopefully someone can update the documentation with an example.

**Comment by vsylvestre** [comment] 2019-10-23 14:23
But wouldn't we want `publicPath` as well? I think it could be useful to be able to set it in the same way that we do `webpack.output.publicPath`.

**Comment by mykt0ngc0** [comment] 2020-03-10 12:13
These are the workarounds: 👇

1. https://github.com/webpack-contrib/mini-css-extract-plugin/issues/403#issuecomment-529142424 by @TheBoroer
2. https://github.com/webpack-contrib/mini-css-extract-plugin/issues/403#issuecomment-537272340 by @alessiofachechi

**Comment by evilebottnawi** [comment] 2020-08-19 15:28
It is not bug, it is misleading, `publicPath` setup publicPath inside `CSS` (for `url`/etc), not for extracted file in runtime generated code, here example how you can achieve original request https://github.com/webpack-contrib/mini-css-extract-plugin/issues/403#issuecomment-537272340, I will update docs

**Closed** 2020-10-09 14:02 UTC
