### ISSUE TITLE
Support modifying filename

### ISSUE THREAD

**Issue by lcxfs1991** [webpack-contrib/mini-css-extract-plugin#91] opened 2018-04-06 17:05 UTC
https://github.com/webpack-contrib/extract-text-webpack-plugin#modify-filename

Wondering if this plugin could support this feature the same as `extract-text-webpack-plugin`.

**Comment by glen-84** [comment] 2018-04-06 17:14
Duplicate of #67.

**Closed** 2018-04-08 06:44 UTC
