### ISSUE TITLE
Module build failed (from ./node_modules/css-loader/dist/cjs.js): CssSyntaxError

### ISSUE THREAD

**Issue by gabrielf7** [webpack-contrib/mini-css-extract-plugin#549] opened 2020-07-17 15:22 UTC
I'm integrating the CSS from index.css and pure.css into the dist folder in just one styles.css file

However, when I use the mini-css-extract-plugin it returns that ERROR below.

Do I need to configure the cjs.js file?

(I am learning to configure webpack.config.js and chose to use a framework called Pure.css)

> pwa-react@1.0.0 build C:\Users\...\Desktop\pwa-react\frontend
> webpack --mode production

Hash: c6cdf7f06d380e10998f
Version: webpack 4.43.0
Time: 4594ms
Built at: 2020-07-17 11:54:41
 3 assets
Entrypoint main = styles.css index_bundle.js
 [8] (webpack)/buildin/global.js 472 bytes {0} [built]
 [9] ./src/css/index.css 625 bytes {0} [built]
[10] ./node_modules/css-loader/dist/cjs.js!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./src/css/index.css 301 bytes {0} [built] [failed] [1 error]
[11] ./src/css/pure-min.css 628 bytes {0} [built]
[12] ./node_modules/css-loader/dist/cjs.js!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./src/css/pure-min.css 301 bytes {0} [built] [failed] [1 error]
[13] ./src/index.jsx + 1 modules 344 bytes {0} [built]
     | ./src/index.jsx 265 bytes [built]
     | ./src/img/favicon.ico 59 bytes [built]
    + 10 hidden modules

ERROR in ./src/css/index.css (./node_modules/css-loader/dist/cjs.js!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./src/css/index.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

> 1 | // extracted by mini-css-extract-plugin
    | ^

 @ ./src/css/index.css 2:26-192
 @ ./src/index.jsx

ERROR in ./src/css/pure-min.css (./node_modules/css-loader/dist/cjs.js!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js!./src/css/pure-min.css)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(1:1) Unknown word

> 1 | // extracted by mini-css-extract-plugin
    | ^

 @ ./src/css/pure-min.css 2:26-195
 @ ./src/index.jsx

...

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! pwa-react@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the pwa-react@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
...

Webpack.config.js file

const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require("html-webpack-plugin");
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  mode: 'production',
  entry: path.join(__dirname, 'src/index.jsx'),
  output: {
    filename: 'index_bundle.js',
    path: path.join(__dirname, 'dist')
  },
  resolve: {
    extensions: [".js",".jsx"]
  },
  plugins: [
    new HtmlWebpackPlugin({...}),
    new MiniCssExtractPlugin({
      filename: "styles.css"
    })
  ],
  module: {       
    rules: [
      {
        test: /.jsx?$/i,
        exclude: /node_modules/,
        include: path.join(__dirname, 'src'),
        use: [
          {
            loader: 'babel-loader',
            options: {
              "presets": [
                ["@babel/preset-env", {
                  "modules": false
                }], "@babel/react"
              ]
            }  
          }
        ]
      },
      {
        test: /\.(jpe?g|ico|png|gif|svg)$/i,
        use: [
          {
            loader: 'file-loader?name=img/[name].[ext]'
          }
        ]
      },
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"] 
      },
      {
        test: /\.css$/i,
        use: [
          MiniCssExtractPlugin.loader,
          "css-loader"
        ],
      },
    ],
  },
  devServer: {...}
};

**Comment by evilebottnawi** [comment] 2020-07-17 15:35
Closing due to inactivity. Please test with latest version and feel free to reopen if still regressions. Thanks!

**Comment by evilebottnawi** [comment] 2020-07-17 15:35
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment] 2020-07-17 15:36
You should not use `style-loader` and `mini-css-extract-plugin` together, please look at docs

**Closed by evilebottnawi** 2020-07-17 15:35 UTC
